### ISSUE TITLE
Chrome Extension isn't working properly

### ISSUE THREAD

**Issue by bigtechplanet** [carolinebuttet/rotary-radio#1]
Opening the extension on the website (radiooooo.com), you notice that the functions to the decade work really well, but the same can't be said to the changing country part since the code in main.js doesn't seem to be working. In the case that it works for you just fine, I'd appreciate some help to understand my situation, because reading radiooooo.com's code hasn't lead me into conclusions for this problem (so far). Appreciate the help still, and a very creative idea.

**Comment by carolinebuttet** [comment]
Hey @bigtechplanet , 
Thanks for pointing this out!
Indeeed the extension was not working properly, this is due to radiooooo.com's new HTML version.
I have pushed a fix in the repo, you can find the new code that should work fine.
Let me know if this works for you !

**Comment by bigtechplanet** [comment]
It works exactly as intended now!
Thank you!
